In [3]:
import numpy as np


[[47 10 52 ... 64 26 21]
 [ 9 47 50 ... 61 52 16]
 [62 65 45 ... 11 50 32]
 ...
 [67  1 28 ... 51 14 30]
 [50 49 63 ... 15  6 19]
 [ 3 50  9 ... 31 41 30]]


In [ ]:
A = np.random.randint(70, size=(50,50))
print (A)

In [5]:
rows = np.random.randint(50, size=(150))
columns = np.random.randint(50, size=(150))
B = 


A[rows, columns]

array([20, 52,  9, 40, 58,  8, 47, 60, 69, 48, 53, 44, 31, 15, 37, 48, 58,
       57, 68, 38, 57, 33, 36,  1, 35, 36, 65, 50, 52, 10, 44,  6, 32, 47,
       67, 11, 56, 60,  3, 10, 42, 14,  2, 62, 49, 31, 60, 10, 21, 27, 55,
       43, 52, 59, 46, 49, 66, 12, 49, 50, 63, 30, 43, 23, 40, 18,  2, 16,
       56,  5, 44, 27, 35,  2, 34,  5, 26, 52, 51,  9, 57, 41, 59, 50,  9,
       20, 20, 37, 57, 24,  3, 44, 20,  9, 59, 62, 38, 12, 50,  0, 50, 27,
        8, 20, 52, 34, 67, 57, 12,  2, 25,  8, 48,  4, 39,  1, 24, 64, 66,
       52,  0, 14,  5, 52, 31, 43, 27, 15, 34,  2, 21, 32, 12, 53, 46, 52,
       63, 35, 49, 45,  7, 35, 22, 60, 64, 20, 47,  9, 37, 31])

In [48]:
position_vector = np.column_stack((rows[:5], columns[:5]))
print (position_vector)

[[ 7 36]
 [ 9 11]
 [ 5 42]
 [23  9]
 [44 19]]


In [50]:
b = np.asarray(position_vector)
print (b)

[[ 7 36]
 [ 9 11]
 [ 5 42]
 [23  9]
 [44 19]]


In [54]:
A[b[0].values]

AttributeError: 'numpy.ndarray' object has no attribute 'values'

In [45]:
[A[i] for i in position_vector]

[array([[35, 61, 20, 12, 36, 40, 46, 48, 49, 35,  2, 21, 42, 41, 38, 25,
         28, 47, 48,  6,  7,  7, 23, 40, 15,  3,  8, 34, 58, 25, 25,  3,
         50,  7, 68, 65, 20, 45, 69, 31, 35, 24, 36, 12, 29, 21,  3, 43,
         35, 58],
        [26, 16, 60, 23, 62, 25, 38,  1, 14, 67, 54, 23, 19,  5, 30,  1,
         50, 39, 39, 30, 65, 55, 37, 15, 38, 10, 55, 19,  9, 38, 63, 67,
         48, 49,  9, 59,  1, 17, 60, 24, 16, 37, 12, 21, 29, 67,  9, 15,
         22, 36]]),
 array([[59, 44, 55, 27, 54, 10, 34, 18, 66, 46, 42, 52, 44, 23,  4,  6,
          6, 64, 21, 68, 67, 46, 34, 65, 36, 22, 30, 41, 26, 59,  9, 53,
         51, 16, 57, 65, 14, 59, 42, 35, 31, 38, 56, 17, 32, 66, 21, 60,
         53, 56],
        [16, 13, 61, 62, 60, 13, 23, 33, 68,  5, 14, 63, 67, 32,  1, 65,
         63, 25, 18, 61, 60, 32, 12, 28, 30, 58, 52, 57, 53, 36, 30, 55,
         12, 55, 49, 11, 19, 50, 44, 24, 12,  5, 34, 63, 24, 20,  9, 63,
         20, 35]]),
 array([[ 8, 21,  5, 23, 26, 66, 33,  1,  2, 48,

In [9]:
A[4,18]

31

In [ ]:
plt.hist(rvs, density=True)

x = np.linspace(rv.ppf(0.001),
                rv.ppf(0.999), 100)
plt.plot(x, 
         rv.pdf(x),
         'r-',
         lw=5,
         alpha=0.6,
         label='gumbel_r',)
plt.grid(True)
plt.legend()